# Generated by Django 3.2.7 on 2022-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.DecimalField(blank=b'I00\n', decimal_places=0, max_digits=10, null=b'I00\n')),
                ('Categoría', models.IntegerField(blank=b'I00\n', choices=[(1, 'Nominas'), (2, 'Facturas'), (3, 'Arrendamiento'), (4, 'Pago de dividendos')], null=b'I00\n')),
                ('Bolsillo_Afectado', models.IntegerField(blank=b'I00\n', choices=[(1, 'Cuenta corriente Davivienda'), (2, 'Cuenta corriente Bancolombia'), (3, 'Nequi'), (4, 'Daviplata'), (5, 'Efectivo (Caja)')], null=b'I00\n')),
                ('Nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.DecimalField(blank=b'I00\n', decimal_places=0, max_digits=10, null=b'I00\n')),
                ('Categoría', models.IntegerField(blank=b'I00\n', choices=[(1, 'Prestamo'), (2, 'Only Fans'), (3, 'Chaturbate'), (4, 'Streamcams'), (5, 'Streamcams1')], null=b'I00\n')),
                ('Bolsillo_Afectado', models.IntegerField(blank=b'I00\n', choices=[(1, 'Cuenta corriente Davivienda'), (2, 'Cuenta corriente Bancolombia'), (3, 'Nequi'), (4, 'Daviplata'), (5, 'Efectivo (Caja)')], null=b'I00\n')),
                ('Nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
