# Generated by Django 4.0.4 on 2022-05-01 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25, unique=b'I01\n', verbose_name='Nombre bolsillo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoría_Egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25, unique=b'I01\n', verbose_name='Nombre Categoría')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoría_Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25, unique=b'I01\n', verbose_name='Nombre Categoría')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Valor', models.DecimalField(blank=b'I00\n', decimal_places=0, max_digits=10, null=b'I00\n')),
                ('Nombre', models.CharField(blank=b'I00\n', max_length=30, null=b'I00\n')),
                ('Bolsillo_Afectado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contabilidad.bolsillo')),
                ('Categoría', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contabilidad.categoría_ingresos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_ing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Valor', models.DecimalField(blank=b'I00\n', decimal_places=0, max_digits=10, null=b'I00\n')),
                ('Nombre', models.CharField(blank=b'I00\n', max_length=30, null=b'I00\n')),
                ('Bolsillo_Afectado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contabilidad.bolsillo')),
                ('Categoría', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contabilidad.categoría_egresos')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Egreso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
