# Generated by Django 3.2.7 on 2022-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='Nombre',
            field=models.CharField(blank=b'I00\n', max_length=30, null=b'I00\n'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='Nombre',
            field=models.CharField(blank=b'I00\n', max_length=30, null=b'I00\n'),
        ),
    ]
