# Generated by Django 3.2.7 on 2022-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
