# Generated by Django 3.2.7 on 2022-03-30 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0002_auto_20220330_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egreso',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='egreso',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
